import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { MainSidebar } from "@/components/main/sidebar-main";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/components/main/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex">
                <SidebarProvider>
                    <TooltipProvider>
                        <MainSidebar />
                        <SidebarInset>
                            <Navbar />
                            <SidebarTrigger className="opacity-20 hover:opacity-100 transition-opacity duration-300 ease-in-out" />
                            {children}
                        </SidebarInset>
                    </TooltipProvider>
                </SidebarProvider>
            </body>
        </html>
    );
}
